%% Enumeration definitions
% Copyright 2017 The MathWorks, Inc.

% Define the required Enums for codegen structure
Simulink.defineIntEnumType('HAL_ultrasound_command_t',{...
    'ULTRASOUND_CMD_NO_CMD',...
    'ULTRASOUND_CMD_SET_MODE',...
    'ULTRASOUND_CMD_SET_NB_PULSES',...
    'ULTRASOUND_CMD_SET_VOLTAGE_MODE',...
    'ULTRASOUND_CMD_SET_NB_PULSES_AND_TENSION_MODE',...
    'ULTRASOUND_CMD_SET_FREQUENCY',...
    'ULTRASOUND_CMD_START',...
    'ULTRASOUND_CMD_STOP'},...
    [0;1;2;4;6;8;16;32]);
Simulink.defineIntEnumType('HAL_BLDC_motor_command_t',{...
    'BLDC_CMD_NO_CMD',...
    'BLDC_CMD_START',...
    'BLDC_CMD_STOP',...
    'BLDC_CMD_RUN',...
    'BLDC_CMD_CLEAR',...
    'BLDC_CMD_REBOOT_BLDC',...
    'BLDC_CMD_LED'},...
    [0;1;2;3;4;5;6]);